### ISSUE TITLE
nav item to open in a new tab

### ISSUE THREAD

**Issue by br3ana** [geoneo1/SimpleWebcomicTheme#5]
On my tumblr I have a "shop" item on my navbar, it is a redirect page, but I want to redirect it to a new tab, I've tried everything and it doesn't work

**Comment by geoneo1** [comment]
Hey, Tumblr does not give you an option to open links in new tabs. It is common practice to allow the user to make the choice. However, if you want to make an individual page open in a new tab, the best way is to include the link straight into the code.

Go to Edit HTML, search for `{block:HasPages}`
Above that (and below `{/block:IfShowHomeLink}`) you can add your custom link. Remember to wrap it in `<li>` eg 
`<li><a href="http://yourshop.com" title="Shop" target="_blank">Shop</a></li>`

Hope that helps, let me know if I can explain anything further.
