### ISSUE TITLE
Page bodies are smaller than post size

### ISSUE THREAD

**Issue by thirdpotato** [geoneo1/SimpleWebcomicTheme#6]
for some reason the page bodies are only 500px wide even though the wrapper of the whole page is 1080px. How do I fix this?

**Comment by geoneo1** [comment]
Hey, all the content is 60% of the wrapper. To change the content width go to Tumblr > Edit theme > Advanced options > in the _Add custom CSS_ field copy and paste the following:

```
article > *, div#disqus_thread, section#notes { width: 60%; }

@media only screen and (max-width: 680px) {
  article > *, div#disqus_thread, section#notes { width: 70%; }
}

@media only screen and (max-width: 480px) {
  article > *, div#disqus_thread, section#notes { width: 90%; }
}
```
In the example above I am using the default percentages, feel free to change them to your liking. It is best that you stick to percentages, but you can use px, if you prefer. 

Hope that helps, let me know if I can explain anything further.

**Comment by thirdpotato** [comment]
Ah thank you so much!


~*B. Alexander*
*Illustrator, Cartoonist*
*View Portfolio* <http://portfolio.thirdpotato.com> | *LinkedIn*
<http://www.linkedin.com/profile/view?id=73352703&locale=en_US&trk=tab_pro>
