### ISSUE TITLE
Call to https://modernizr.com/downloads/modernizr-latest.js results in 404

### ISSUE THREAD

**Issue by pstewartjones** [geoneo1/SimpleWebcomicTheme#7]
There's a reference to https://modernizr.com/downloads/modernizr-latest.js on line 532 - it doesn't seem to affect the display of the theme but it does throw an error in the console as the location is now 404.

**Comment by geoneo1** [comment]
Thanks for the heads up. I have now removed modernizr. I was mostly using it for html5shiv, which I have included separately.
